[package]
name = "borrowed-example"
version = "0.0.0"

[addresses]
std =  "0x1"
borrowed_example = "0x2"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "b718154c93b3556658c8c06341be0cf47957188c"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "b718154c93b3556658c8c06341be0cf47957188c"